{% set name = "gfal2-util" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.cern.ch/dmc/gfal2-util/-/archive/v{{ version }}/gfal2-util-v{{ version }}.tar.gz
  sha256: 258eee96340b9b564e0ff1a2d064d2da8a170ae5d581a3a417a812f3e125b66f

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - python-gfal2

test:
  # source_files:
  #   - test/functional  # [py2k]
  #   - test/functional_py3  # [py3k]
  # requires:
  #   - pytest
  requires:
    - python {{ python_min }}
  imports:
    - gfal2_util
  commands:
    - gfal-cat --help
    - gfal-chmod --help
    - gfal-copy --help
    - gfal-legacy-bringonline --help
    - gfal-legacy-register --help
    - gfal-legacy-replicas --help
    - gfal-legacy-unregister --help
    - gfal-ls --help
    - gfal-mkdir --help
    - gfal-rename --help
    - gfal-rm --help
    - gfal-save --help
    - gfal-stat --help
    - gfal-sum --help
    - gfal-xattr --help
    # - pytest

about:
  home: http://dmc.web.cern.ch/projects/gfal2-utils
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: GFAL2 utility tools
  description: |
    GFAL 2 utils are a group of command line tools for file manipulations
    with any protocol managed by gfal2
  doc_url: https://gitlab.cern.ch/dmc/gfal2-util#list-of-commands
  dev_url: https://gitlab.cern.ch/dmc/gfal2-util/

extra:
  recipe-maintainers:
    - chrisburr
