{% set name = "gfal2-util" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.cern.ch/dmc/gfal2-util/-/archive/v{{ version }}/gfal2-util-v{{ version }}.tar.gz
  sha256: 2fe3be4594bc9775c03972136dcde855743c06cb79b28f62da1ec8937c1ddb29

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - python-gfal2

test:
  # source_files:
  #   - test/functional  # [py2k]
  #   - test/functional_py3  # [py3k]
  # requires:
  #   - pytest
  imports:
    - gfal2_util
  commands:
    - gfal-cat --help
    - gfal-chmod --help
    - gfal-copy --help
    - gfal-legacy-bringonline --help
    - gfal-legacy-register --help
    - gfal-legacy-replicas --help
    - gfal-legacy-unregister --help
    - gfal-ls --help
    - gfal-mkdir --help
    - gfal-rename --help
    - gfal-rm --help
    - gfal-save --help
    - gfal-stat --help
    - gfal-sum --help
    - gfal-xattr --help
    # - pytest

about:
  home: http://dmc.web.cern.ch/projects/gfal2-utils
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: GFAL2 utility tools
  description: |
    GFAL 2 utils are a group of command line tools for file manipulations
    with any protocol managed by gfal2
  doc_url: https://gitlab.cern.ch/dmc/gfal2-util#list-of-commands
  dev_url: https://gitlab.cern.ch/dmc/gfal2-util/

extra:
  recipe-maintainers:
    - chrisburr
